// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/generate-env.mjs — DO NOT EDIT MANUALLY
// Generated at: 2026-03-13T17:04:02.477Z
// Stack: sruti-dev
// ─────────────────────────────────────────────────────────────────────────────
export const environment = {
  production: false,
  apiBaseUrl: 'https://d6ch5dpl33.execute-api.ap-south-1.amazonaws.com/v1',
  amplify: {
    region:           'ap-south-1',
    userPoolId:       'ap-south-1_MlIrxyVfj',
    userPoolClientId: '64apllsrm28plaujjuuraco73l',
    identityPoolId:   'ap-south-1:8c01f723-80ba-4275-ba8d-48ed8f7b3d7d',
  },
  s3: {
    bucket:  'sruti-dev-audio-assets',
    region:  'ap-south-1',
    baseUrl: 'https://d3mdtr9dikmvgc.cloudfront.net',
  },
  web: {
    url: 'https://d1x1b7nb5k45cc.cloudfront.net',
  },
  featureFlags: {
    aiCoach:       true,
    guruClassroom: true,
    offlineMode:   true,
  },
};
