// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/generate-env.mjs — DO NOT EDIT MANUALLY
// Generated at: 2026-03-20T03:53:11.357Z
// Stack: swara-prod
// ─────────────────────────────────────────────────────────────────────────────
export const environment = {
  production: true,
  apiBaseUrl: 'https://8jod66td5b.execute-api.us-east-1.amazonaws.com/v1',
  amplify: {
    region:           'us-east-1',
    userPoolId:       'us-east-1_LCQUEOEdU',
    userPoolClientId: '5ihctma9671kru63obntl5o9ln',
    identityPoolId:   'us-east-1:95756ff5-668a-42fa-8bf0-f21e3f17de40',
  },
  s3: {
    bucket:  'swara-prod-audio-assets-use1',
    region:  'us-east-1',
    baseUrl: 'https://d14q5xsqfrymnw.cloudfront.net',
  },
  web: {
    url: 'https://dnyhpf7im0ppf.cloudfront.net',
  },
  featureFlags: {
    aiCoach:       true,
    guruClassroom: true,
    offlineMode:   true,
  },
  liveUpdate: {
    manifestUrl: 'https://d3nsubq9bsdq94.cloudfront.net/manifest.json',
  },
  enableAnalytics: true,
  firebase: {
    apiKey:            '',
    authDomain:        '',
    projectId:         '',
    storageBucket:     '',
    messagingSenderId: '',
    appId:             '',
    measurementId:     '',
  },
};
