// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/generate-env.mjs — DO NOT EDIT MANUALLY
// Generated at: 2026-03-14T05:35:49.754Z
// Stack: sruti-dev
// ─────────────────────────────────────────────────────────────────────────────
export const environment = {
  production: false,
  apiBaseUrl: 'https://vu6tcny761.execute-api.us-east-1.amazonaws.com/v1',
  amplify: {
    region:           'us-east-1',
    userPoolId:       'us-east-1_yKk4ZG7xB',
    userPoolClientId: '634tgsfrgqjamshalrr2g52pj7',
    identityPoolId:   'us-east-1:16ec054f-7312-4427-ab86-5b491851ac9d',
  },
  s3: {
    bucket:  'sruti-dev-audio-assets-use1',
    region:  'us-east-1',
    baseUrl: 'https://d2llcbx0zcbb1a.cloudfront.net',
  },
  web: {
    url: 'https://dlfmvipmlfhsm.cloudfront.net',
  },
  featureFlags: {
    aiCoach:     true,
    offlineMode: true,
  },
  liveUpdate: {
    manifestUrl: 'https://REPLACE_AFTER_CDK_DEPLOY/manifest.json',
  },
  enableAnalytics: false,
  // Firebase config — not used in dev (analytics disabled).
  // In prod this block is injected by generate-env.mjs from CI secrets.
  firebase: {
    apiKey:            '',
    authDomain:        '',
    projectId:         '',
    storageBucket:     '',
    messagingSenderId: '',
    appId:             '',
    measurementId:     '',
  },
};
