// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/generate-env.mjs — DO NOT EDIT MANUALLY
// Generated at: 2026-03-16T15:28:54.945Z
// Stack: sruti-prod
// ─────────────────────────────────────────────────────────────────────────────
export const environment = {
  production: true,
  apiBaseUrl: 'https://8ipbhfi00c.execute-api.us-east-1.amazonaws.com/v1',
  amplify: {
    region:           'us-east-1',
    userPoolId:       'us-east-1_INCAabl97',
    userPoolClientId: '2er8dnp3unemdkhq03df52e1s6',
    identityPoolId:   'us-east-1:172f100c-0294-491f-b424-4b258438624f',
  },
  s3: {
    bucket:  'sruti-prod-audio-assets-use1',
    region:  'us-east-1',
    baseUrl: 'https://d3sj1eh6z1o7g4.cloudfront.net',
  },
  web: {
    url: 'https://d1f644lz4vig94.cloudfront.net',
  },
  featureFlags: {
    aiCoach:       true,
    guruClassroom: true,
    offlineMode:   true,
  },
  liveUpdate: {
    manifestUrl: 'https://d36pxm4nxhwid8.cloudfront.net/manifest.json',
  },
  enableAnalytics: true,
  firebase: {
    apiKey:            '',
    authDomain:        '',
    projectId:         '',
    storageBucket:     '',
    messagingSenderId: '',
    appId:             '',
    measurementId:     '',
  },
};
