#!/usr/bin/env node
/**
 * generate-env.mjs
 *
 * Reads CloudFormation stack outputs and writes the Angular environment file.
 *
 * Usage:
 *   node scripts/generate-env.mjs <stage>
 *   stage: "dev" | "prod"
 *
 * Requires AWS credentials to be set in the environment (done by CI).
 */

import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const stage = process.argv[2];
if (!['dev', 'prod'].includes(stage)) {
  console.error('Usage: node scripts/generate-env.mjs <dev|prod>');
  process.exit(1);
}

const stackName = `sruti-${stage}`;
const region    = process.env['AWS_REGION'] ?? 'us-east-1';

console.log(`\n📦 Reading CloudFormation outputs from stack: ${stackName} (${region})\n`);

let rawOutputs;
try {
  const result = execSync(
    `aws cloudformation describe-stacks --stack-name ${stackName} --region ${region} --query "Stacks[0].Outputs" --output json`,
    { encoding: 'utf8' },
  );
  rawOutputs = JSON.parse(result);
} catch (err) {
  console.error(`❌ Failed to read stack outputs: ${err.message}`);
  process.exit(1);
}

/** @type {Record<string, string>} */
const out = {};
for (const { OutputKey, OutputValue } of rawOutputs) {
  out[OutputKey] = OutputValue;
}

console.log('✅ Stack outputs found:', Object.keys(out).join(', '));

const isProd = stage === 'prod';

const content = `// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/generate-env.mjs — DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}
// Stack: ${stackName}
// ─────────────────────────────────────────────────────────────────────────────
export const environment = {
  production: ${isProd},
  apiBaseUrl: '${out['ApiUrl']}/v1',
  amplify: {
    region:           '${region}',
    userPoolId:       '${out['UserPoolId']}',
    userPoolClientId: '${out['UserPoolClientId']}',
    identityPoolId:   '${out['IdentityPoolId']}',
  },
  s3: {
    bucket:  '${isProd ? 'sruti-prod-audio-assets-use1' : 'sruti-dev-audio-assets-use1'}',
    region:  '${region}',
    baseUrl: '${out['AudioCdnUrl']}',
  },
  web: {
    url: '${out['WebUrl']}',
  },
  featureFlags: {
    aiCoach:       true,
    guruClassroom: true,
    offlineMode:   true,
  },
};
`;

const envFile = isProd
  ? resolve(__dirname, '../apps/mobile-app/src/environments/environment.prod.ts')
  : resolve(__dirname, '../apps/mobile-app/src/environments/environment.ts');

writeFileSync(envFile, content, 'utf8');
console.log(`\n✅ Written → ${envFile}\n`);
